name: 'Badge replace'
description: 'Replace badge in readme'
inputs:
  cypress-outcome:
    description: 'Cypress outcome'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/badge.sh ${{ inputs.cypress-outcome }}
      shell: bash
